#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
# sync firefox before executing
firefox-sync &

# I hate cursors
unclutter -idle 10 &
xrdb -merge ~/.Xresources
exec awesome

# sync firefox before shutting down
firefox-sync
